### ISSUE TITLE
Index out of range exception when creating ColumnModification with identical column/key names

### ISSUE THREAD

**Issue by HighQualityWaschbaer** [Valentin-Kaiser/go-dbase#1]
When creating a column modification where the original column name and the target name (key) are equal, an index out of range exception occurs when trying to read the resulting dbf rows.

```
2022/08/29 15:32:51 Importing technicians...
2022/08/29 15:32:51 [importer] [0] interruption: runtime error: index out of range [-1]
exit status 0xc000013a
```

```go
log.Print("Importing technicians...")

dbf, err := dbase.Open(filepath.Join(manager.config.DBPath, "DATABASE.dbf"), &dbase.Win1250Converter{})
	if err != nil {
		log.Panicf(err.Error())
	}
	defer dbf.Close()

	dbf.SetTrimspacesDefault(true)
	dbf.SetColumnModification(dbf.ColumnPos("TECHNR"), true, "ID", nil)
	dbf.SetColumnModification(dbf.ColumnPos("Name"), true, "Name", nil) //crashes because of this line

	for !dbf.EOF() {
		row, err := dbf.Row()
		if err != nil {
			log.Panicf(err.Error())
		}
		dbf.Skip(1)

		if row.Deleted {
			continue
		}
...
}
```
The original column names in the dbf table:
![The original column names](https://user-images.githubusercontent.com/51928003/187213805-30243db5-55b2-446d-a207-dcf921e3482c.png)

The target struct for reference:
```go
type Technician struct {
	ID        uint64 `gorm:"primaryKey" json:"ID"`
	Name      string `gorm:"not null" json:"Name"`
	CreatedAt time.Time
	UpdatedAt time.Time
}
```

Reading the rows works perfectly fine when removing the line, but this action should not cause any problems...

**Comment by Valentin-Kaiser** [comment]
The error does not occur because the name is identical, but because there is no column with the name "Name". dbf.ColumnPos("Name") returns -1 and thus the index is out of range. I will, for ease of use, include a check to validate that the index is valid.
