### ISSUE TITLE
Add support for CDX index files

### ISSUE THREAD

**Issue by razvanphp** [Valentin-Kaiser/go-dbase#128]
We are using this lib successfully to edit / insert into a DBF File Type: 0x30 (Visual FoxPro), windows-1252 encoding, that has a corresponding .CDX index file. We can insert into the DB, but we need to somehow update the index afterwards.

Is this already possible? If yes, please let me know how, otherwise, would it be possible to be implemented?

I would definitely help with contribution, but I'm not a go developer, ChatGPT is my friend for this small tool 🙂 

Thank you!
R

**Comment by Valentin-Kaiser** [comment]
So far it is not possible to read or write any index files (.idx, .cdx). The library allows to write tables, but is not really made for that. It was implemented mainly for reading. 

It is possible to implement the reading and writing of index files. However, this is not trivial and time-consuming. 
I'll find out more about the index files and their structure and work something out.  If I actually start with the implementation, it will take a few weeks or months.

**Comment by razvanphp** [comment]
For my use-case and hopefully others too, it's enough a way to trigger index rebuild / refresh, no need for reading and editing the index. Maybe that is easier to implement.

I can try to implement something and test with chatgpt if you can provide a boilerplate API that I should follow.

Thank you for taking the time for this!
R

**Comment by Valentin-Kaiser** [comment]
The library does not use a Visual Foxpro executable, which means that it is not possible to trigger reindexing.
Reindexing would have to be implemented in the library.

**Comment by razvanphp** [comment]
Hmm, we are retrofiting an old app, maybe that one bundles the foxpro executable or a dll we can use for reindexing?

**Comment by Valentin-Kaiser** [comment]
I can't answer that for you. But I don't think it's that easy. Executing Visual Foxpro commands directly via the cli is not possible, so you can't run any indexing command.
