### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by Serhioromano** [Valentin-Kaiser/go-dbase#147]
I used go-dbf and that created a file and opened it in Excel but there is a bug it cannot read file because one byte is lost somewhere. I tryied to use your package. It looked much more advanced. I created file and inserted rows. But I cannot open it with Excel. It say that file extension does not match file format.

- OS: Windows
- Go version: 1.23.4
- Package version: v1.12.4

Here is my code

```go
if _, err := os.Stat(dbFile); errors.Is(err, os.ErrNotExist) {
	file, err := dbase.NewTable(
		dbase.FoxProVar,
		&dbase.Config{
			Filename:   dbFile,
			Converter:  dbase.NewDefaultConverter(charmap.Windows1250),
			TrimSpaces: true,
		},
		columns(),
		64,
		nil,
	)
	if err != nil {
		log.Fatal(err)
	}
	file.Close()
}
// Open the example database table.
table, err := dbase.OpenTable(&dbase.Config{
	Filename:   dbFile,
	TrimSpaces: true,
	WriteLock:  true,
})
if err != nil {
	log.Fatal(err)
}
defer table.Close()

fmt.Printf(
	"Last modified: %v Columns count: %v Record count: %v File size: %v \n",
	table.Header().Modified(0),
	table.Header().ColumnsCount(),
	table.Header().RecordsCount(),
	table.Header().FileSize(),
)

e := Entry{
	Adr:    0,
	Before: 250,
	After:  1250,
	Date:   time.Now(),
	Time:   time.Now(),
	Action: 0,
}

row, err := table.RowFromStruct(e)
if err != nil {
	log.Fatal(err)
}

// Add the new row to the database table.
err = row.Write()
if err != nil {
	log.Fatal(err)
}
```

**Comment by Valentin-Kaiser** [comment]
Hello Serhioromano,
What is the goal you are trying to achieve?
The file created by this library should be a foxpro/dbase file with a .dbf file extension. I am not aware that the file can be used with Microsoft Excel.

**Comment by Serhioromano** [comment]
Usualy you can open DBF files in Excel. But file created by this library cannot be opened in Excel. If cannot recognize it as DBF file.

I write a small windows service that periodically stores data to that file and then it is imported to CRM. I successfully can create DBF file with `go-dbf` that is opened by Excel, but then those files cannot be opened by `go-dbf` itself. I switched to your library, it can create and open files and add records successfully, but cannot open in Microsoft Office Excel.

**Comment by Serhioromano** [comment]
Additional information. I can created DBF file which I can open in Excel with `dbase.FoxPro2Memo` type. But then I cannot open it with your library again

```
2024/12/29 13:36:24 untested DBF file version: 245 (0xf5)
exit status 1
```
For instance, if I use type `dbase.FoxBasePlus` then I can open DBF in Excel

![2024-12-29_13-54-04](https://github.com/user-attachments/assets/a4818e6f-ef19-444a-8598-6b019d368aab)

But your library cannot open it to insert records with error  `2024/12/29 13:53:52 untested DBF file version: 3 (0x3)`

Or I can add new records with your library with other type, but cannot open in Excel

![2024-12-29_13-52-18](https://github.com/user-attachments/assets/a023f723-7d63-4750-8f82-83366681a1e1)

**Comment by Valentin-Kaiser** [comment]
https://github.com/Valentin-Kaiser/go-dbase/blob/86fc47a5be301a0a9a73728fd15c5e7e9eaaf745/dbase/constants.go#L9-L31

https://github.com/Valentin-Kaiser/go-dbase/blob/86fc47a5be301a0a9a73728fd15c5e7e9eaaf745/dbase/dbase.go#L25

**Comment by Valentin-Kaiser** [comment]
But I am sure that there is a better solution for your problem. dBase and Foxpro are not exactly up to date and this package is there to migrate data from legacy software. That's why I haven't tested many dbase versions. 

If you want to go deeper into the topic I recommend this reference from 2006: https://learn.microsoft.com/en-us/previous-versions/visualstudio/foxpro/h9f898ae(v=vs.71)

If you have any changes or bug fixes you would like to contribute, please feel free to open a pull request.

Translated with DeepL.com (free version)

**Comment by Serhioromano** [comment]
how to see DB version of a current file? I have an example file I want to open it and check what version it is.

**Comment by Serhioromano** [comment]
how to see DB version of a current file? I have an example file I want to open it and check what version it is.

> But I am sure that there is a better solution for your problem. dBase and Foxpro are not exactly up to date and this package is there to migrate data from legacy software. That's why I haven't tested many dbase versions.
> 
> If you want to go deeper into the topic I recommend this reference from 2006: https://learn.microsoft.com/en-us/previous-versions/visualstudio/foxpro/h9f898ae(v=vs.71)
> 
> If you have any changes or bug fixes you would like to contribute, please feel free to open a pull request.

If during the work, I'll need to apply some fixes of changes I'll submit a PR.

**Comment by Serhioromano** [comment]
Through the error I have discovered that my example file is version 0x03. So, I created `dbase.FoxBasePlus` file. I can open it in Excel. And with `Untested` property I can insert rows there. But unfortunately, only `dbase.NewColumn("DATEW", dbase.Date, 0, 0, false)` field is populated and other fields are empty.

```go
func columns() []*dbase.Column {
	adr, err := dbase.NewColumn("ADR", dbase.Integer, 2, 0, false)
	if err != nil {
		panic(err)
	}

	before, err := dbase.NewColumn("WBBFORE", dbase.Integer, 2, 0, false)
	if err != nil {
		panic(err)
	}

	after, err := dbase.NewColumn("WBAFTER", dbase.Integer, 2, 0, false)
	if err != nil {
		panic(err)
	}

	dt, err := dbase.NewColumn("DATEW", dbase.Date, 0, 0, false)
	if err != nil {
		panic(err)
	}

	tm, err := dbase.NewColumn("TIMEW", dbase.DateTime, 2, 0, false)
	if err != nil {
		panic(err)
	}

	action, err := dbase.NewColumn("ACT", dbase.Integer, 2, 0, false)
	if err != nil {
		panic(err)
	}

	return []*dbase.Column{
		adr,
		before,
		after,
		dt,
		tm,
		action,
	}
}
```

This is my structure.

Could you please look into it? It would take much less time for you to debug it than me. Although I know a little go (2 month experiance), i know nothing about DBF files.

**Comment by Serhioromano** [comment]
I have managed everything to work with files version 03. thank you.
