### ISSUE TITLE
Support other dbase/foxpro files (.dbc, .dbf, .frx, .lbx, .mnx, .pjx, .scx, .vcx)

### ISSUE THREAD

**Issue by Valentin-Kaiser** [Valentin-Kaiser/go-dbase#31]
> Visual FoxPro uses tables to store data that defines different file types. The following list includes the file types that are saved as tables:
>
> - Database (.dbc)
> - Form (.scx)
> - Label (.lbx)
> - Menu (.mnx)
> - Project (.pjx)
> - Report (.frx)
> - Table (.dbf)
> - Visual class library (.vcx)
>
>You can use and browse these files in the same way that you browse any table file because these files are actually tables.

https://learn.microsoft.com/en-us/previous-versions/visualstudio/foxpro/st4a0s68(v=vs.80)

**Comment by Valentin-Kaiser** [comment]
Currently, tables (DBF) and the associated memo (FPT) files are supported and database tables (DBC) and the associated container (DCT) files can be opened to the extent that the tables belonging to the database can be read. Relations and other data are not read because I do not know how to interpret them. I have not yet found any documentation on this.

**Comment by nicola-spb** [comment]
@Valentin-Kaiser  I got error
`dbase-io-opentable-5:dbase-io-preparedbf-2:dbase-io-validatefileversion-1:untested DBF file version: 3 (0x3)`

Do you will support this version?

**Comment by Valentin-Kaiser** [comment]
Hi @nicola-spb
According to the visual studio foxpro documentation, 3 (0x3) is not a valid file type. See the [Table Header Record Structure](https://learn.microsoft.com/en-us/previous-versions/visualstudio/foxpro/st4a0s68(v=vs.80)).
This error simply means that this file type was not tested by me, you can easily bypass the check by setting Untested to true in the [configuration](https://pkg.go.dev/github.com/Valentin-Kaiser/go-dbase@v1.8.3/dbase#Config).
