### ISSUE TITLE
Add read ReaderCloser

### ISSUE THREAD

**Issue by nicola-spb** [Valentin-Kaiser/go-dbase#49]
Please add in `OpenTable` function reading from `io.ReadCloser` interface. 
I have files in archive and func return io.ReaderCloser. I think it will be useful.

**Comment by Valentin-Kaiser** [comment]
Hello @nicola-spb,
Thanks for your request, that sounds like a useful extension, I'll have a look at it. And provide feedback on feasibility and duration.

Kind regards,
Valentin-Kaiser

**Comment by Valentin-Kaiser** [comment]
Hello @nicola-spb,
could you test the whole thing with the [v1.9.0 pre-release](https://github.com/Valentin-Kaiser/go-dbase/releases/tag/v1.9.0)?
You can now pass a GenericIO Struct as a second parameter to the OpenTable function. This struct has two attributes, one for the DBF and one for the related FPT file if available.
Please give me feedback if it works and if you encounter any errors.
