### ISSUE TITLE
`undefined: syscall.Handle` errors on macOS

### ISSUE THREAD

**Issue by onderweg** [Valentin-Kaiser/go-dbase#56]
I'm not sure if there is an issue with my Go environment on macOS, but when I try to use the module (for example by running the examples), I get `syscall.Handle` errors:

```
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/io.go:13:27: undefined: syscall.Handle
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/io.go:14:27: undefined: syscall.Handle
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/io.go:121:28: undefined: syscall.Handle
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/io.go:149:31: undefined: syscall.Handle
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/io.go:151:36: undefined: syscall.Handle
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/io.go:199:32: undefined: syscall.Handle
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/table.go:76:40: undefined: syscall.Handle
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/table.go:88:32: undefined: syscall.Handle
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/interpreter.go:98:33: undefined: syscall.Handle
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/interpreter.go:104:36: undefined: syscall.Handle
/Users/macuser/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/io.go:151:36: too many errors
```

Is there a known issue with running this module on macOS? (M1,  Ventura 13.1)

**Comment by Valentin-Kaiser** [comment]
I have personally never tested it under macOS, only under Windows and Linux systems. I will take a closer look at the problem.

But please check if you are using the latest release.
I can see in your output that you are using an old version: `github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977`

**Comment by onderweg** [comment]
Thanks!

>I can see in your output that you are using an old version

Mmmm, strange. This:
```
go get github.com/Valentin-Kaiser/go-dbase/dbase@latest 
```

results for me in release `v0.0.0-20220622120602-842944cf2977 `

**Comment by Valentin-Kaiser** [comment]
Try `go get github.com/Valentin-Kaiser/go-dbase@latest`

**Comment by onderweg** [comment]
Yep, that fixed it. Thanks.

I followed the read me:

>Installation
>go get github.com/Valentin-Kaiser/go-dbase/dbase

Now I have both the latest version, and the error is gone :)

**Comment by Valentin-Kaiser** [comment]
Very nice, I'll close the issue then.

**Comment by denispol** [comment]
Hi, still encountering this issue as I'm using a workflow automation tool where Go is bunbled and we don't have the possibility to include any latest tag (packages are automatically downloaded from last release):

```
ExecutionErr: ExitCode: 1, last log lines:
call.Handle
../../../cache/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/table.go:88:32: undefined: syscall.Handle
../../../cache/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/interpreter.go:98:33: undefined: syscall.Handle
../../../cache/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/interpreter.go:104:36: undefined: syscall.Handle
../../../cache/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/io.go:151:36: too many errors
```

Running Azure Linux in Kubernetes

**Comment by Valentin-Kaiser** [comment]
I needed to fuck around a bit with the releases/tags and the dbase directory in my module, but it should be solved now.

```bash
go get github.com/Valentin-Kaiser/go-dbase@latest
go: added github.com/Valentin-Kaiser/go-dbase v1.12.0

go get github.com/Valentin-Kaiser/go-dbase/dbase@latest
go: added github.com/Valentin-Kaiser/go-dbase v1.12.0


```

[submodule versioning](https://go.dev/ref/mod#vcs-version)
> If a module is defined in a subdirectory within the repository, that is, the [module subdirectory](https://go.dev/ref/mod#glos-module-subdirectory) portion of the module path is not empty, then each tag name must be prefixed with the module subdirectory, followed by a slash. For example, the module golang.org/x/tools/gopls is defined in the gopls subdirectory of the repository with root path golang.org/x/tools. The version v0.4.0 of that module must have the tag named gopls/v0.4.0 in that repository.
