### ISSUE TITLE
Datetime conversion does not work

### ISSUE THREAD

**Issue by HighQualityWaschbaer** [Valentin-Kaiser/go-dbase#67]
I have a foxpro table with a column(EINGABEAM) that holds datetime information in the format MM/DD/YY HH:mm:ss AM/PM that i want to read.

Now when i am setting up the dbase reader
```go
dbf, err := dbase.OpenTable(&dbase.Config{
		Filename:   filepath.Join(FILE_DIR, FILENAME),
		TrimSpaces: true,
	})
dbf.SetColumnModificationByName("EINGABEAM", &dbase.Modification{TrimSpaces: true, ExternalKey: "creationDate", Convert: imp.convDateToTimestamp})
```
and try to read its value:
```go
val, _ := row.ValueByName("EINGABEAM")
		log.Debugf("%+v", val)
```
val is always equal to
`0001-01-01 00:00:00 +0000 UTC`
no matter the actual value of the field (for example [01/13/2009 12:59:38 PM]).

The "EINGABEAM" field is of type DateTime with a width of 8.
Is this a bug or am i doing something wrong?

**Comment by Valentin-Kaiser** [comment]
Can you append the definition of the convDateToTimestamp function?

**Comment by HighQualityWaschbaer** [comment]
```go
func (imp *Importer) convDateToTimestamp(value interface{}) (interface{}, error) {
	date, err := time.Parse("2006-01-02 15:04:05 -0700 UTC", fmt.Sprint(value))
	if err != nil {
		return nil, fmt.Errorf("Could not parse date: " + err.Error())
	}
	return date.Unix(), err
}
```

Please keep in mind that i can access the incorrect information before trying to parse the datetime in my own function by converting the row to a struct:

```go
row, err := dbf.Next()
if err != nil {
	log.Errorf("could not obtain row from database: %v", err.Error())
	continue
}
if row.Deleted {
	continue
}
val, _ := row.ValueByName("EINGABEAM")
log.Debugf("%+v", val)
```
